// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCi3OMHIpzevumGKOlbp9tiWd1EMMdNe-Y',
    appId: '1:993674284850:web:32bdcc5f37b3a4550b512b',
    messagingSenderId: '993674284850',
    projectId: 'omsp-d1fe9',
    authDomain: 'omsp-d1fe9.firebaseapp.com',
    storageBucket: 'omsp-d1fe9.firebasestorage.app',
    measurementId: 'G-GQWTBD79VN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBejxdQ3V8hMsMf8IqXegrEKD_klIcwJ8k',
    appId: '1:993674284850:android:aa1578a60b4dfff90b512b',
    messagingSenderId: '993674284850',
    projectId: 'omsp-d1fe9',
    storageBucket: 'omsp-d1fe9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXOk0gIS3ymuhQCRLDXwYa0c-dVGABbOk',
    appId: '1:993674284850:ios:59a3ee85e1ccc4e00b512b',
    messagingSenderId: '993674284850',
    projectId: 'omsp-d1fe9',
    storageBucket: 'omsp-d1fe9.firebasestorage.app',
    iosBundleId: 'com.tecxpert.tms',
  );
}
